import { Header } from "@/components/Header"
import "../../styles/globals.scss"
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import Providers from "@/components/Providers"

const roboto = Roboto({
      weight: ['400' , '700' , '900'],
      style: ['normal' , 'italic'],
      subsets: ['latin']
  })

export const metadata: Metadata = {
  title: 'ig.news',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, } : { children: React.ReactNode}) {
  return (
    <html lang="pt-br">
      <Providers>
        <body className={roboto.className}>
            <Header />
            {children}
        </body>
      </Providers>
    </html>
  )
}
