import { Header } from "@/components/Header"
import "../../styles/globals.scss"
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import { SessionProvider as NextAuthProvider } from 'next-auth/react';

const roboto = Roboto({
      weight: ['400' , '700' , '900'],
      style: ['normal' , 'italic'],
      subsets: ['latin']
  })

export const metadata: Metadata = {
  title: 'ig.news',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, } : { children: React.ReactNode} , {
    Component , pageProps
  }) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <NextAuthProvider session={session}>
          <Header />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
